# Generated by Django 5.2.3 on 2025-06-25 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(default='class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Join_date', models.DateField()),
                ('classroom', models.ManyToManyField(related_name='classrooms', to='app_Admin.classroom')),
                ('subject', models.ManyToManyField(related_name='Subjects', to='app_Admin.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('email', models.EmailField(default='@', max_length=254, unique=True)),
                ('contact_no', models.CharField(default='XXXXXXXXXXX', max_length=11)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ManyToManyField(related_name='subjects', to='app_Admin.subject')),
                ('teacher', models.ManyToManyField(related_name='teachers', to='app_Admin.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tragetClass', models.ManyToManyField(related_name='Classroom', to='app_Admin.classroom')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attadence', models.CharField(choices=[('PRESENT', 'present'), ('ABSENT', 'absent'), ('LEAVE', 'leave')])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.student')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.teacher')),
            ],
        ),
    ]
