# Generated by Django 5.2.3 on 2025-06-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(default='9', on_delete=django.db.models.deletion.CASCADE, to='app_Admin.classroom'),
        ),
    ]
