# Generated by Django 5.2.3 on 2025-06-25 08:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Admin', '0002_subject_classroom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attadence',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attadence',
            new_name='attendance',
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tragetClass', models.ManyToManyField(related_name='Classroom', to='app_Admin.classroom')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Admin.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
