# Generated by Django 5.2.3 on 2025-06-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Admin', '0003_rename_attadence_attendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='taken_by',
            new_name='teacher',
        ),
    ]
